; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Sun Feb 25 2024 15:08:49 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


