; homeu.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Sun Feb 25 2024 15:08:49 GMT-0500 (Eastern Standard Time)
;G91               ; relative positioning
;G1 H1 X-375 F1800 ; move quickly to X axis endstop and stop there (first pass)
;G1 H2 X5 F6000    ; go back a few mm
;G1 H1 X-375 F360  ; move slowly to X axis endstop once more (second pass)
;G90               ; absolute positioning

