; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Sun Feb 25 2024 15:08:49 GMT-0500 (Eastern Standard Time)
G91               ; relative positioning
G1 H1 Y318 F1800  ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y-5 F6000   ; go back a few mm
G1 H1 Y318 F360   ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning

