; homeu.g
; called to home the U axis
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Sun Feb 25 2024 15:08:49 GMT-0500 (Eastern Standard Time)
G91               ; relative positioning
G91               ; relative positioning
G1 H1 U-205 F600 ; move Z down until the endstop is triggered
G92 U0            ; set Z position to axis minimum (you may want to adjust this)
