; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Sun Feb 25 2024 15:08:50 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

